#Department Highest Salary
#/* Write your PL/SQL query statement below */
#
#SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY FROM
#EMPLOYEE E,
#DEPARTMENT D,
#(SELECT MAX(SALARY) AS SALARY, DEPARTMENTID FROM EMPLOYEE GROUP BY DEPARTMENTID) S
#WHERE
#E.DEPARTMENTID = D.ID
#AND E.DEPARTMENTID = S.DEPARTMENTID
#AND E.SALARY = S.SALARY