-- Employees With Missing Information
/* Write your PL/SQL query statement below */
SELECT EMPLOYEE_ID
FROM
(SELECT E.EMPLOYEE_ID, E.NAME, S.SALARY FROM
EMPLOYEES E LEFT JOIN SALARIES S
ON E.EMPLOYEE_ID = S.EMPLOYEE_ID) A
WHERE A.SALARY IS NULL
UNION ALL
SELECT EMPLOYEE_ID
FROM
(SELECT S.EMPLOYEE_ID, E.NAME, S.SALARY FROM
SALARIES S LEFT JOIN EMPLOYEES E
ON E.EMPLOYEE_ID = S.EMPLOYEE_ID) A
WHERE A.NAME IS NULL
ORDER BY 1